name: Secure Image Factory

on: [push]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    # Added: Necessary for pushing to GHCR in 2026
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-secure-app:${{ github.sha }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.35.0 
        with:
          image-ref: 'my-secure-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        if: success()
        run: |
          # Convert the repository name to lowercase to avoid Docker errors
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker tag my-secure-app:${{ github.sha }} $IMAGE_ID:latest
          docker push $IMAGE_ID:latest